name: front_medizin
description: "Aplicación médica FrontMedizin"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0+2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^2.1.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0 
  flutter_native_splash: ^2.4.6 # Paquete para cambiar nombre del paquete

flutter_native_splash:
  color: "#19d8e9"
  image: assets/favicon1.png
  android_12:
    image: assets/favicon1.png
    color: "#19d8e9"  # Paquete para cambiar nombre del paquete

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon1.png"
  adaptive_icon_background: "#19D8EA"

flutter:
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    
  uses-material-design: true