name: front_medizin
description: "Aplicación médica FrontMedizin"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^2.1.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0  # Paquete para cambiar nombre del paquete

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"
  adaptive_icon_background: "#19D8EA"

flutter:
  assets:
    - assets/logo.png
    - assets/logoblanco.png
    - assets/bandera.png
    - assets/favicon.png
    - assets/google.png
    - assets/face.png
    - assets/producto1.png
    - assets/producto2.png
    - assets/producto3.png
    - assets/farmacia.png
    - assets/salud.png
    - assets/higiene.png
    - assets/bebe.png
    - assets/siencere.png
    - assets/snack.png
    - assets/bucal.png
    - assets/hogar.png
    - assets/banner.png
    - assets/cocacola.png
    - assets/ordinary.png
    - assets/genven.png
    - assets/acetaminofen_500mg.png
    - assets/acetaminofen_650mg.png
    - assets/farmacia2.png
    - assets/siencere2.png
    - assets/higiene2.png
    - assets/bebe2.png
    - assets/snack2.png
    - assets/hogar2.png
    - assets/malestar.png
    - assets/siencere2.png
    - assets/higiene2.png
    - assets/bebe2.png
    - assets/snack2.png
    - assets/hogar2.png
    - assets/torsilax.png
    - assets/atamel.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    
  uses-material-design: true