name: front_medizin
description: "Aplicación médica FrontMedizin"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^2.1.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0  # Paquete para cambiar nombre del paquete

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"

flutter:
  assets:
    - assets/logo.png
    - assets/logoblanco.png
    - assets/bandera.png
    - assets/favicon.png
    - assets/google.png
    - assets/face.png
  uses-material-design: true