name: front_medizin
description: "Aplicación médica FrontMedizin"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^2.1.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0 
  flutter_native_splash: ^2.4.6 # Paquete para cambiar nombre del paquete

flutter_native_splash:
  color: "#19d8e9"
  image: assets/favicon1.png
  android_12:
    image: assets/favicon1.png
    color: "#19d8e9"  # Paquete para cambiar nombre del paquete

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon1.png"
  adaptive_icon_background: "#19D8EA"

flutter:
  assets:
    - assets/logo.png
    - assets/logoblanco.png
    - assets/bandera.png
    - assets/favicon1.png
    - assets/google.png
    - assets/face.png
    - assets/producto1.png
    - assets/producto2.png
    - assets/producto3.png
    - assets/farmacia.png
    - assets/salud.png
    - assets/higiene.png
    - assets/bebe.png
    - assets/siencere.png
    - assets/snack.png
    - assets/bucal.png
    - assets/hogar.png
    - assets/banner.png
    - assets/cocacola.png
    - assets/ordinary.png
    - assets/genven.png
    - assets/acetaminofen_500mg.png
    - assets/acetaminofen_650mg.png
    - assets/farmacia2.png
    - assets/siencere2.png
    - assets/higiene2.png
    - assets/bebe2.png
    - assets/snack2.png
    - assets/hogar2.png
    - assets/malestar.png
    - assets/siencere2.png
    - assets/higiene2.png
    - assets/bebe2.png
    - assets/snack2.png
    - assets/hogar2.png
    - assets/torsilax.png
    - assets/atamel.png
    - assets/acetaminofen2.png
    - assets/inicio.png
    - assets/categoria.png
    - assets/creditos.png
    - assets/servicios.png
    - assets/favoritos.png
    - assets/compras.png
    - assets/acerca.png
    - assets/ayuda.png
    - assets/notificaciones.png
    - assets/contraseña.png
    - assets/direccion.png
    - assets/datos.png
    - assets/foto.png
    - assets/borrar.png
    - assets/settings.png
    - assets/contactar.png
    - assets/farmacia1.jpg
    - assets/farmacia2.jpg
    - assets/farmacia3.png
    - assets/farmacia4.jpg
    - assets/copiar.png
    - assets/subirarchivo.png
    - assets/error.png
    - assets/pagoexitoso.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    
  uses-material-design: true